db:
  image: mysql
  expose:
    - "3306"
  volumes:
    - /opt/db:/var/lib/mysql
  environment:
    - MYSQL_DATABASE=bigmom_db
    - MYSQL_ROOT_PASSWORD=11111111  

web:
  build: .
  command: python manage.py runserver 0.0.0.0:8000
  volumes:
    - /opt/bigmom:/code/bigmom
  ports:
    - "8000:8000"
  links:
    - db
  