# -*- coding: utf-8 -*-
# Generated by Django 1.11.7 on 2017-11-09 08:11
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('loaf', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='question',
            name='user_id',
            field=models.BigIntegerField(default=0, verbose_name='创建者'),
        ),
    ]
