# -*- coding: utf-8 -*-
# Generated by Django 1.11.7 on 2017-11-09 08:17
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('loaf', '0002_question_user_id'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='question',
            name='user_id',
        ),
    ]
